name: Maven test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn clean package --batch-mode -DskipTests -e -B

      - name: Test
        run: mvn test -Dmaven.test.failure.ignore=true -e -B

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
